### ISSUE TITLE
Add option to disable the plugin or not fail when fileNotFound

### ISSUE THREAD

**Issue by Kotlin-Native** [razvn/jacoco-to-cobertura-gradle-plugin#20]
I have a multimodule project with one module which has only interfaces. In that project, no report is created and the plugin and full pipe fails, because the plugin itself is applied to all subprojects. It would be a lot of copy paste work to have it everywhere, aside of one module.
For that, it would be nice if it can be disabled there, or that you can simply configure that it does not fail on missing file and instead simply skip it.

**Comment by Frontrider** [comment]
I had some experience with that, and as far as I can see it may not possible.

**Comment by razvn** [comment]
Any chance to get an exemple project to test with.

**Comment by bddckr** [comment]
With #19 merged and 1.2.0 released, this issue will only occur by default [if you have applied the `JacocoPlugin` to the subproject as well](https://github.com/razvn/jacoco-to-cobertura-gradle-plugin/blob/1cfd1d8ba78e5f18535a89cae7ceff09c594f0a1/src/main/kotlin/JacocoToCoberturaPlugin.kt#L38-L39).

Should you be applying `JacocoPlugin` and thus turn on this project's plugin, you can now disable the conversion task not to get the exception:
```kotlin
tasks.named(JacocoToCoberturaPlugin.TASK_NAME) { enabled = false }
```

Depending on your scenario, you may use `onlyIf` instead of `enabled`.

**Comment by martinweu** [comment]
@bddckr 
I would still vouch for the option to disable the missing file error, because if you have a multi module project you sometimes have modules without tests (so no coverage) but share the build and test configuration. Gralde test and JaCoCo work fine in modules without tests, only JaCoCo won't generate a coverage report, which then would lead to the file not found error.

**Comment by Frontrider** [comment]
The thing that happens in these cases, is that gradle reads the property marked with `@InputFile`, finds that it is indeed missing then fails the task. You can't disable the error itself, because you have no control over it.

As stated, `onlyIf` and `enabled` are the solutions here. It should not be included in the plugin by default to avoid creating false positives.

**Comment by bddckr** [comment]
I agree with @Frontrider. I don't see how that would work while still ensuring all other users of this plugin get an error. The user should be told that they've probably misconfigured something.

Instead of adding an option to configure this behavior (or similar), consider changing your build logic. Applying a plugin like this one to (sub)projects that don't need it is a waste of configuration (and potentially execution) time in Gradle at a minimum. At worst, you'll have to get more plugins to offer some kind of "applied, but not doing anything" option for your use cases. So maybe consider not applying JaCoCo and this plugin in the first place to projects that don't need it? Your convention plugin could have a boolean flag to make this conditional, or you could perhaps split out the plugin to offer, e.g., `TestProjectPlugin` as well as a `CoveredTestProjectPlugin` or something.

I understand where this feature request is coming from, but my personal experience is that applying a plugin and then trying to "disable it" is something many plugins don't support. That's what _`apply`ing_ the plugin is handling.

**Comment by martinweu** [comment]
Thanks, @bddckr and @Frontrider I guess this would be the wrong way. I can follow your arguments and see how this is a problem with gradle configuration. I can find a way to make it work for me. Because this plugin will mostly be used in combination with JaCoCo, I think it would be cool to match the "fault-tolerant" behavior of JaCoCo.

**Comment by razvn** [comment]
I’ll try to see what I can do, maybe by putting the inputFile as an optional.

**Comment by Frontrider** [comment]
> I’ll try to see what I can do, maybe by putting the inputFile as an optional.

`@Optional` only checks if the value was set or not. If you set it to a file that is missing then it won't change anything. I spent enough time trying to make that work to know.

**Comment by razvn** [comment]
Thanks for your time. I can see that in my tests too.

Seems hard achieve that unless going back and not using inputFile as a InputFile and just as `String` or `File?`… 

I’ll try some more things to see if that can be done.

**Comment by bddckr** [comment]
Not using `InputFile` (with a supported type like `RegularFile(Property)`) will break the configuration cache (and maybe even the up-to-date check). It's like the system is telling us we're doing the wrong thing when trying to deviate from stock Gradle behavior here 😅 

If you really wanna continue with making this a thing, I highly suggest making it configurable. If a user asks this plugin's task to convert a file, why shouldn't it fail if that file isn't found?! Why hide the error and leave it up to them to wonder? 🤔

---

Anyway, [here](https://github.com/gradle/gradle/blob/247964621a71ad299b1ec0141827bf589b39a9cc/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoReportBase.java#L62-L72)'s how the JaCoCo task does it - via `onlyIf`!

**Comment by Frontrider** [comment]
> Seems hard achieve that unless going back and not using inputFile as a InputFile and just as `String` or `File?`…

`@InputFile` or `@InputFiles` are the correct ways to do it.

**Comment by razvn** [comment]
As long as Gradle does not fixes the issue with `@Optional` support for `@InputFile` https://github.com/gradle/gradle/issues/2016
I don't plan to change the format from @InputFile to make it work.

As a workaround you can use `onlyIf` in the configuration of the plugin to run it only if the file does exist.

For exemple: 
```kotlin
tasks.jacocoToCobertura {
	dependsOn(tasks.koverXmlReport)
	val jacocoReport = project.layout.buildDirectory.file("reports/kover/report_that_does_not_exist.xml")
	onlyIf {
		jacocoReport.get().asFile.exists()
	}
	inputFile.set(jacocoReport)
	outputFile.set(project.layout.buildDirectory.file("reports/kover/cobertura.xml"))
}
```
Using this configuration `jacocoToCopertura` task won't run if the the file does not exist.
I think it's a easy workaournd that fixed the issue.
