### ISSUE TITLE
Task should do nothing if input file doesn't exist

### ISSUE THREAD

**Issue by remal** [razvn/jacoco-to-cobertura-gradle-plugin#26]
We apply `jacoco` plugin to every Gradle project. However, some projects don't have tests. Could you please add `@org.gradle.api.tasks.Optional` annotation to the getter `JacocoToCoberturaTask.inputFile` so that `JacocoToCoberturaTask` is skipped if the input file doesn't exist.

**Comment by razvn** [comment]
Unfortuntally doesn't seem to work @Optional on inputFiles.
I did it in the last releasea hoping it will fix it but realized it does non ;(
There's an old opened issue about it... 
https://github.com/gradle/gradle/issues/2016

**Comment by razvn** [comment]
I agree with what is said in the discussion in #20 issue, it should be `InputFile` but I agree should be possible to set it as @Optional, so build won't fail because of that, but Gradle doesn't seem to agree so far. 

So I'll keep it this way, because there's a workaround. I'll update the `readme` to specify it, by using `onlyIf` in the task definition: 

For exemple: 
```kotlin
tasks.jacocoToCobertura {
	dependsOn(tasks.koverXmlReport)
	val jacocoReport = project.layout.buildDirectory.file("reports/kover/report_that_does_not_exist.xml")
	onlyIf {
		jacocoReport.get().asFile.exists()
	}
	inputFile.set(jacocoReport)
	outputFile.set(project.layout.buildDirectory.file("reports/kover/cobertura.xml"))
}
```
Using this configuration `jacocoToCopertura` task won't run if the the file does not exist.
I think it's a easy workaournd that fixed the issue.
